# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0193311e45056ca90dddbceaa226b54686d6feae0bfaf4d449ce529c4db3240921884b204956a0581bf2dd104eba505933a76128c66014d4ff337759c47b7ab5

test:
  secret_key_base: ec39fc1f287bc04ea36097243b4512c9cf88fcc457fb983d31570d0bcae572df1cd6bc1915371bf1450b1ffc835324945e6838d24b969e42d45b7107973fb244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
